apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-all.yaml
  - allow-same-namespace.yaml
  - allow-from-openshift-ingress.yaml
  - allow-from-monitoring.yaml
  - allow-dns-egress.yaml
  - allow-ollama-model-pull-egress.yaml
