apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vehicle-booking-stage

resources:
  - ../../base

replicas:
  - name: vehicle-booking
    count: 1

commonLabels:
  env: stage
