apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vehicle-booking-prod

resources:
  - ../../base

replicas:
  - name: vehicle-booking
    count: 2

commonLabels:
  env: prod
