apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql
  - redis
  - ollama
  - api-gateway
  - web-ui
  - networkpolicy
  - rbac
  - services/catalog-svc
  - services/location-svc
  - services/traveler-svc
  - services/pricing-svc
  - services/booking-svc
  - services/payment-svc
  - services/chatbot-svc
  - services/mcp-server

commonLabels:
  app.kubernetes.io/part-of: car-rental
