apiVersion: v1
kind: ResourceQuota
metadata:
  name: car-rental-dev-quota
  namespace: car-rental-dev
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 4Gi
    pods: "20"
    count/deployments.apps: "15"
    persistentvolumeclaims: "3"
