apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vehicle-booking
  namespace: openshift-gitops
spec:
  description: Vehicle booking POC project
  sourceRepos:
    - "https://github.com/esarath/ocp-argocd-vechicle-booking-poc.git"
  destinations:
    - namespace: "vehicle-booking-stage"
      server: https://kubernetes.default.svc
    - namespace: "vehicle-booking-prod"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: policy
      kind: "*"
    - group: route.openshift.io
      kind: "*"
