apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicle-booking-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vehicle-booking
  source:
    repoURL: "https://github.com/esarath/ocp-argocd-vechicle-booking-poc.git"
    targetRevision: main
    path: apps/vehicle-booking/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: vehicle-booking-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
